### ISSUE TITLE
symfony/console version

### ISSUE THREAD

**Issue by koehnlein** [supseven-at/t3ext-yaml-configuration#4]
In latest master, the `ImportTableCommand` and the `ExportTableCommand` both use the constant `Command::SUCCESS` which is only available in symfony/console:^5.1 https://github.com/symfony/console/blame/5.1/Command/Command.php#L33 but seems not in older versions.

TYPO3 v10 requires symfony/console in version `^4.4 || ^5.0`: https://github.com/TYPO3/typo3/blob/10.4/composer.json#L66

For a full compatibility with TYPO3 v10, I guess the return values in `ImportTableCommand` and `ExportTableCommand` should be changed from `Command::SUCCESS` simply to `0`

**Comment by koehnlein** [comment]
The constants are available since 5.1, I updated my comment above, where I first mentioned, they would be available since 6.0

**Comment by koehnlein** [comment]
An alternative way to solve this, would be to define requirement `symfony/console:^5.1` in composer.json. But you would have to always maintain theses line in future versions of your extension. And on the other hand, you would not support all TYPO3 v10 installations.

**Comment by josefglatz** [comment]
merged
